In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df=pd.read_csv(filepath_or_buffer="./players_20.csv",sep=",",header=0).rename(columns=str.lower)
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [8]:
df.shape

(18278, 104)

In [9]:
df.columns

Index(['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob',
       'height_cm', 'weight_kg', 'nationality', 'club',
       ...
       'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'],
      dtype='object', length=104)

In [10]:
df1=df[["short_name","age","height_cm","weight_kg","nationality","club","overall","potential","value_eur","wage_eur","player_positions","power_jumping","power_long_shots"]]
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [11]:
df1.shape

(18278, 13)

In [13]:
df1.sort_values("overall",ascending=False).head()

,short_name,age,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,power_jumping,power_long_shots
0,L. Messi,32,170,72,Argentina,FC Barcelona,94,94,95500000,565000,"RW, CF, ST",68,94
1,Cristiano Ronaldo,34,187,83,Portugal,Juventus,93,93,58500000,405000,"ST, LW",95,93
2,Neymar Jr,27,175,68,Brazil,Paris Saint-Germain,92,92,105500000,290000,"LW, CAM",61,84
3,J. Oblak,26,188,87,Slovenia,Atlético Madrid,91,93,77500000,125000,GK,78,12
4,E. Hazard,28,175,74,Belgium,Real Madrid,91,91,90000000,470000,"LW, CF",56,80

In [26]:
#Sigue aqquí
realmadrid=df1[df1.club=="Real Madrid"]
realmadrid.shape

(33, 13)

In [20]:
realmadrid.sort_values("overall",ascending=False)

,short_name,age,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,power_jumping,power_long_shots
4,E. Hazard,28,175,74,Belgium,Real Madrid,91,91,90000000,470000,"LW, CF",56,80
8,L. Modrić,33,172,66,Croatia,Real Madrid,90,90,45000000,340000,CM,68,82
18,Sergio Ramos,33,184,82,Spain,Real Madrid,89,89,31500000,300000,CB,93,62
28,T. Courtois,27,199,96,Belgium,Real Madrid,88,89,48000000,235000,GK,68,17
36,T. Kroos,29,183,76,Germany,Real Madrid,88,88,57000000,330000,CM,30,86
42,Casemiro,27,185,84,Brazil,Real Madrid,87,89,53500000,240000,CDM,87,81
46,K. Benzema,31,185,81,France,Real Madrid,87,87,45000000,285000,"CF, ST",77,76
53,K. Navas,32,185,80,Costa Rica,Real Madrid,87,87,30500000,195000,GK,74,13
62,Isco,27,176,79,Spain,Real Madrid,86,87,51000000,245000,"CAM, CM, LW",61,84
76,R. Varane,26,191,81,France,Real Madrid,85,90,45000000,205000,CB,79,53
94,Carvajal,27,173,73,Spain,Real Madrid,85,86,38000000,205000,RB,77,36
100,G. Bale,29,185,82,Wales,Real Madrid,85,85,37500000,250000,"RW, LW, ST",86,90
101,Marcelo,31,174,75,Brazil,Real Madrid,85,85,28000000,205000,LB,77,70
106,J. Rodríguez,27,180,75,Colombia,Real Madrid,85,85,40500000,225000,"CAM, CM, RM",46,92
161,L. Jović,21,182,85,Serbia,Real Madrid,83,89,36500000,155000,ST,75,76
178,Marco Asensio,23,182,76,Spain,Real Madrid,83,87,34000000,180000,"LW, RW",58,84
277,Nacho Fernández,29,180,76,Spain,Real Madrid,82,83,21000000,165000,"CB, LB, RB",81,28
332,Éder Militão,21,186,78,Brazil,Real Madrid,81,88,23000000,105000,"CB, RB",86,42
403,Lucas Vázquez,28,173,70,Spain,Real Madrid,81,81,18000000,180000,"RW, RM",68,76
424,F. Mendy,24,180,73,France,Real Madrid,80,86,18000000,115000,LB,78,64
437,Odriozola,23,176,66,Spain,Real Madrid,80,85,17500000,115000,RB,71,59
568,Vinícius Jr.,18,176,73,Brazil,Real Madrid,79,92,22500000,60000,LW,75,68
636,Mariano,25,180,76,Dominican Republic,Real Madrid,79,82,16000000,145000,ST,92,82
1009,F. Valverde,20,182,78,Uruguay,Real Madrid,77,85,13000000,86000,"CM, LM, CDM",44,77
1256,Rodrygo,18,174,64,Brazil,Real Madrid,76,89,14000000,47000,"LW, RW, ST",73,70
2286,Lucas Silva,26,182,80,Brazil,Real Madrid,74,77,6500000,88000,"CDM, CM",71,73
2652,Brahim,19,171,68,Spain,Real Madrid,73,86,7500000,58000,"LW, RW",65,65
4757,T. Kubo,18,173,67,Japan,Real Madrid,70,87,3700000,21000,"RM, CF",54,52
5676,Javi Hernández,21,182,72,Spain,Real Madrid,69,83,2200000,33000,"CB, LWB",69,63
8777,Sergio López,20,179,66,Spain,Real Madrid,66,82,1300000,20000,RB,61,59
8898,Fidalgo,22,175,68,Spain,Real Madrid,66,76,1000000,27000,"CAM, CM, LM",51,48
9922,De la Fuente,20,179,78,Spain,Real Madrid,65,81,1100000,18000,CB,69,39
13116,Altube,19,188,85,Spain,Real Madrid,62,82,550000,6000,GK,53,8

In [21]:
realmadrid.sort_values("value_eur",ascending=False)

,short_name,age,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,power_jumping,power_long_shots
4,E. Hazard,28,175,74,Belgium,Real Madrid,91,91,90000000,470000,"LW, CF",56,80
36,T. Kroos,29,183,76,Germany,Real Madrid,88,88,57000000,330000,CM,30,86
42,Casemiro,27,185,84,Brazil,Real Madrid,87,89,53500000,240000,CDM,87,81
62,Isco,27,176,79,Spain,Real Madrid,86,87,51000000,245000,"CAM, CM, LW",61,84
28,T. Courtois,27,199,96,Belgium,Real Madrid,88,89,48000000,235000,GK,68,17
8,L. Modrić,33,172,66,Croatia,Real Madrid,90,90,45000000,340000,CM,68,82
76,R. Varane,26,191,81,France,Real Madrid,85,90,45000000,205000,CB,79,53
46,K. Benzema,31,185,81,France,Real Madrid,87,87,45000000,285000,"CF, ST",77,76
106,J. Rodríguez,27,180,75,Colombia,Real Madrid,85,85,40500000,225000,"CAM, CM, RM",46,92
94,Carvajal,27,173,73,Spain,Real Madrid,85,86,38000000,205000,RB,77,36
100,G. Bale,29,185,82,Wales,Real Madrid,85,85,37500000,250000,"RW, LW, ST",86,90
161,L. Jović,21,182,85,Serbia,Real Madrid,83,89,36500000,155000,ST,75,76
178,Marco Asensio,23,182,76,Spain,Real Madrid,83,87,34000000,180000,"LW, RW",58,84
18,Sergio Ramos,33,184,82,Spain,Real Madrid,89,89,31500000,300000,CB,93,62
53,K. Navas,32,185,80,Costa Rica,Real Madrid,87,87,30500000,195000,GK,74,13
101,Marcelo,31,174,75,Brazil,Real Madrid,85,85,28000000,205000,LB,77,70
332,Éder Militão,21,186,78,Brazil,Real Madrid,81,88,23000000,105000,"CB, RB",86,42
568,Vinícius Jr.,18,176,73,Brazil,Real Madrid,79,92,22500000,60000,LW,75,68
277,Nacho Fernández,29,180,76,Spain,Real Madrid,82,83,21000000,165000,"CB, LB, RB",81,28
424,F. Mendy,24,180,73,France,Real Madrid,80,86,18000000,115000,LB,78,64
403,Lucas Vázquez,28,173,70,Spain,Real Madrid,81,81,18000000,180000,"RW, RM",68,76
437,Odriozola,23,176,66,Spain,Real Madrid,80,85,17500000,115000,RB,71,59
636,Mariano,25,180,76,Dominican Republic,Real Madrid,79,82,16000000,145000,ST,92,82
1256,Rodrygo,18,174,64,Brazil,Real Madrid,76,89,14000000,47000,"LW, RW, ST",73,70
1009,F. Valverde,20,182,78,Uruguay,Real Madrid,77,85,13000000,86000,"CM, LM, CDM",44,77
2652,Brahim,19,171,68,Spain,Real Madrid,73,86,7500000,58000,"LW, RW",65,65
2286,Lucas Silva,26,182,80,Brazil,Real Madrid,74,77,6500000,88000,"CDM, CM",71,73
4757,T. Kubo,18,173,67,Japan,Real Madrid,70,87,3700000,21000,"RM, CF",54,52
5676,Javi Hernández,21,182,72,Spain,Real Madrid,69,83,2200000,33000,"CB, LWB",69,63
8777,Sergio López,20,179,66,Spain,Real Madrid,66,82,1300000,20000,RB,61,59
9922,De la Fuente,20,179,78,Spain,Real Madrid,65,81,1100000,18000,CB,69,39
8898,Fidalgo,22,175,68,Spain,Real Madrid,66,76,1000000,27000,"CAM, CM, LM",51,48
13116,Altube,19,188,85,Spain,Real Madrid,62,82,550000,6000,GK,53,8

In [24]:
#Para renombrar columnas se ponen entre llaves, y 2 puntos en medio.
realmadrid.rename(columns={"age":"edad"}).head()

,short_name,edad,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,power_jumping,power_long_shots
4,E. Hazard,28,175,74,Belgium,Real Madrid,91,91,90000000,470000,"LW, CF",56,80
8,L. Modrić,33,172,66,Croatia,Real Madrid,90,90,45000000,340000,CM,68,82
18,Sergio Ramos,33,184,82,Spain,Real Madrid,89,89,31500000,300000,CB,93,62
28,T. Courtois,27,199,96,Belgium,Real Madrid,88,89,48000000,235000,GK,68,17
36,T. Kroos,29,183,76,Germany,Real Madrid,88,88,57000000,330000,CM,30,86

In [49]:
realmadrid.rename(columns={"height_cm":"altura_cm"}).head()

,short_name,age,altura_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,power_jumping,power_long_shots
4,E. Hazard,28,175,74,Belgium,Real Madrid,91,91,90000000,470000,"LW, CF",56,80
8,L. Modrić,33,172,66,Croatia,Real Madrid,90,90,45000000,340000,CM,68,82
18,Sergio Ramos,33,184,82,Spain,Real Madrid,89,89,31500000,300000,CB,93,62
28,T. Courtois,27,199,96,Belgium,Real Madrid,88,89,48000000,235000,GK,68,17
36,T. Kroos,29,183,76,Germany,Real Madrid,88,88,57000000,330000,CM,30,86

In [50]:
realmadrid.rename(columns={"players_positions":"posicion"}).head()

,short_name,age,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,power_jumping,power_long_shots
4,E. Hazard,28,175,74,Belgium,Real Madrid,91,91,90000000,470000,"LW, CF",56,80
8,L. Modrić,33,172,66,Croatia,Real Madrid,90,90,45000000,340000,CM,68,82
18,Sergio Ramos,33,184,82,Spain,Real Madrid,89,89,31500000,300000,CB,93,62
28,T. Courtois,27,199,96,Belgium,Real Madrid,88,89,48000000,235000,GK,68,17
36,T. Kroos,29,183,76,Germany,Real Madrid,88,88,57000000,330000,CM,30,86

In [54]:
realmadrid[realmadrid.weight_kg>80]

,short_name,age,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,power_jumping,power_long_shots
18,Sergio Ramos,33,184,82,Spain,Real Madrid,89,89,31500000,300000,CB,93,62
28,T. Courtois,27,199,96,Belgium,Real Madrid,88,89,48000000,235000,GK,68,17
42,Casemiro,27,185,84,Brazil,Real Madrid,87,89,53500000,240000,CDM,87,81
46,K. Benzema,31,185,81,France,Real Madrid,87,87,45000000,285000,"CF, ST",77,76
76,R. Varane,26,191,81,France,Real Madrid,85,90,45000000,205000,CB,79,53
100,G. Bale,29,185,82,Wales,Real Madrid,85,85,37500000,250000,"RW, LW, ST",86,90
161,L. Jović,21,182,85,Serbia,Real Madrid,83,89,36500000,155000,ST,75,76
13116,Altube,19,188,85,Spain,Real Madrid,62,82,550000,6000,GK,53,8

In [55]:
#Crea una muestra aleatoria
#Porcentaje 10%
realmadrid.sample(frac=0.1)

,short_name,age,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,power_jumping,power_long_shots
8777,Sergio López,20,179,66,Spain,Real Madrid,66,82,1300000,20000,RB,61,59
46,K. Benzema,31,185,81,France,Real Madrid,87,87,45000000,285000,"CF, ST",77,76
36,T. Kroos,29,183,76,Germany,Real Madrid,88,88,57000000,330000,CM,30,86

In [56]:
#Valor absoluto 5 unidades
realmadrid.sample(n=5)

,short_name,age,height_cm,weight_kg,nationality,club,overall,potential,value_eur,wage_eur,player_positions,power_jumping,power_long_shots
1256,Rodrygo,18,174,64,Brazil,Real Madrid,76,89,14000000,47000,"LW, RW, ST",73,70
46,K. Benzema,31,185,81,France,Real Madrid,87,87,45000000,285000,"CF, ST",77,76
8777,Sergio López,20,179,66,Spain,Real Madrid,66,82,1300000,20000,RB,61,59
94,Carvajal,27,173,73,Spain,Real Madrid,85,86,38000000,205000,RB,77,36
76,R. Varane,26,191,81,France,Real Madrid,85,90,45000000,205000,CB,79,53